[project]
name = "web-proxy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen-agentchat>=0.7.5",
    "autogen-ext[grpc,mcp,ollama,openai]>=0.7.5",
    "dotenv>=0.9.9",
    "markdown>=3.10",
]
